name: "Documentation: update documentation chatbot"

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build and run
        run: |
          mvn -pl internal/langchain4j-docu-chatbot-updater clean compile exec:java
